services:
  web:
    build: .
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root123456
    volumes:
      - /opt/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
